workflows:
  android-release:
    name: Android Release (with Rust KERI Bridge)
    max_build_duration: 90
    instance_type: linux_x2
    environment:
      flutter: 3.22.0
      java: 17
    scripts:
      - name: Install Rust toolchain and Android targets
        script: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source "$HOME/.cargo/env"
          rustup target add \
            aarch64-linux-android \
            armv7-linux-androideabi \
            x86_64-linux-android \
            i686-linux-android
          cargo install cargo-ndk
          echo "--- Rust version ---"
          rustc --version
          cargo --version
          cargo ndk --version

      - name: Configure Android NDK for Rust
        script: |
          source "$HOME/.cargo/env"
          export ANDROID_NDK_HOME="$ANDROID_SDK_ROOT/ndk/$(ls $ANDROID_SDK_ROOT/ndk/ | sort -V | tail -1)"
          echo "Using NDK: $ANDROID_NDK_HOME"
          echo "ANDROID_NDK_HOME=$ANDROID_NDK_HOME" >> $CM_ENV

      - name: Build Rust library for Android via cargo-ndk
        script: |
          source "$HOME/.cargo/env"
          cd identity_agent_ui/rust
          cargo ndk \
            --target aarch64-linux-android \
            --target armv7-linux-androideabi \
            --target x86_64-linux-android \
            --target i686-linux-android \
            --platform 21 \
            --output-dir ../android/app/src/main/jniLibs \
            build --release
          echo "--- Built .so files ---"
          find ../android/app/src/main/jniLibs -name "*.so" -ls

      - name: Generate flutter_rust_bridge bindings
        script: |
          source "$HOME/.cargo/env"
          cargo install flutter_rust_bridge_codegen --version 2.11.1
          cd identity_agent_ui
          flutter_rust_bridge_codegen generate

      - name: Set up local properties
        script: |
          cd identity_agent_ui
          echo "flutter.sdk=$HOME/programs/flutter" > android/local.properties
          echo "sdk.dir=$ANDROID_SDK_ROOT" >> android/local.properties

      - name: Get Flutter packages
        script: |
          cd identity_agent_ui
          flutter pub get

      - name: Build debug APK
        script: |
          cd identity_agent_ui
          flutter build apk --debug

      - name: Build release APK
        script: |
          cd identity_agent_ui
          flutter build apk --release

    artifacts:
      - identity_agent_ui/build/app/outputs/flutter-apk/*.apk

  ios-release:
    name: iOS Release (with Rust KERI Bridge)
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      flutter: 3.22.0
      xcode: latest
      cocoapods: default
      groups:
        - ios_credentials
      vars:
        BUNDLE_ID: "com.identityagent.identityAgentUi"
    scripts:
      - name: Install Rust toolchain and iOS targets
        script: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source "$HOME/.cargo/env"
          rustup target add aarch64-apple-ios
          rustup target add aarch64-apple-ios-sim
          echo "--- Rust version ---"
          rustc --version
          cargo --version

      - name: Build Rust static library for iOS (device)
        script: |
          source "$HOME/.cargo/env"
          cd identity_agent_ui/rust
          cargo build --release --target aarch64-apple-ios
          echo "--- Built device static library ---"
          ls -lh target/aarch64-apple-ios/release/libidentity_agent_keri.a

      - name: Build Rust static library for iOS (simulator)
        script: |
          source "$HOME/.cargo/env"
          cd identity_agent_ui/rust
          cargo build --release --target aarch64-apple-ios-sim
          echo "--- Built simulator static library ---"
          ls -lh target/aarch64-apple-ios-sim/release/libidentity_agent_keri.a

      - name: Copy Rust libraries to iOS Frameworks
        script: |
          RUST_DIR="identity_agent_ui/rust"
          IOS_DIR="identity_agent_ui/ios"
          LIB="libidentity_agent_keri.a"
          mkdir -p "$IOS_DIR/Frameworks/RustKeri/device"
          mkdir -p "$IOS_DIR/Frameworks/RustKeri/simulator"
          cp "$RUST_DIR/target/aarch64-apple-ios/release/$LIB" \
             "$IOS_DIR/Frameworks/RustKeri/device/$LIB"
          cp "$RUST_DIR/target/aarch64-apple-ios-sim/release/$LIB" \
             "$IOS_DIR/Frameworks/RustKeri/simulator/$LIB"
          echo "--- Libraries placed ---"
          ls -lh "$IOS_DIR/Frameworks/RustKeri/device/$LIB"
          ls -lh "$IOS_DIR/Frameworks/RustKeri/simulator/$LIB"

      - name: Generate flutter_rust_bridge bindings
        script: |
          source "$HOME/.cargo/env"
          cargo install flutter_rust_bridge_codegen --version 2.11.1
          cd identity_agent_ui
          flutter_rust_bridge_codegen generate

      - name: Get Flutter packages
        script: |
          cd identity_agent_ui
          flutter pub get

      - name: Install CocoaPods dependencies
        script: |
          cd identity_agent_ui/ios
          pod install

      - name: Set up iOS code signing
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create
          keychain add-certificates
          xcode-project use-profiles

      - name: Build iOS IPA (release)
        script: |
          cd identity_agent_ui
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist

    artifacts:
      - identity_agent_ui/build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - "Internal Testers"
