workflows:
  android-release:
    name: Android Release (with Rust KERI Bridge)
    max_build_duration: 90
    instance_type: linux_x2
    environment:
      flutter: 3.22.0
      java: 17
    scripts:
      - name: Install Rust toolchain and Android targets
        script: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source "$HOME/.cargo/env"
          rustup target add \
            aarch64-linux-android \
            armv7-linux-androideabi \
            x86_64-linux-android \
            i686-linux-android
          cargo install cargo-ndk
          echo "--- Rust version ---"
          rustc --version
          cargo --version
          cargo ndk --version

      - name: Configure Android NDK for Rust
        script: |
          source "$HOME/.cargo/env"
          export ANDROID_NDK_HOME="$ANDROID_SDK_ROOT/ndk/$(ls $ANDROID_SDK_ROOT/ndk/ | sort -V | tail -1)"
          echo "Using NDK: $ANDROID_NDK_HOME"
          echo "ANDROID_NDK_HOME=$ANDROID_NDK_HOME" >> $CM_ENV

      - name: Install FRB codegen
        script: |
          source "$HOME/.cargo/env"
          cargo install flutter_rust_bridge_codegen --version 2.11.1

      - name: Set up local properties
        script: |
          cd identity_agent_ui
          echo "flutter.sdk=$HOME/programs/flutter" > android/local.properties
          echo "sdk.dir=$ANDROID_SDK_ROOT" >> android/local.properties

      - name: Get Flutter packages
        script: |
          cd identity_agent_ui
          flutter pub get

      - name: Build Rust library for Android via cargo-ndk with FRB codegen
        script: |
          source "$HOME/.cargo/env"
          cd identity_agent_ui/rust
          mkdir -p ../android/app/src/main/jniLibs/arm64-v8a
          mkdir -p ../android/app/src/main/jniLibs/armeabi-v7a
          mkdir -p ../android/app/src/main/jniLibs/x86_64
          mkdir -p ../android/app/src/main/jniLibs/x86

          # Phase 1: Build with dev_skip_frb so FRB codegen can inspect symbols
          echo "--- Phase 1: Building with dev_skip_frb for FRB codegen ---"
          cargo ndk \
            --target aarch64-linux-android \
            --target armv7-linux-androideabi \
            --target x86_64-linux-android \
            --target i686-linux-android \
            --platform 21 \
            --output-dir ../android/app/src/main/jniLibs \
            build --release --features dev_skip_frb

          # Phase 2: Generate FRB bindings (creates src/frb_generated.rs)
          # Requires flutter pub get to have been run first.
          echo "--- Phase 2: Generating FRB bindings ---"
          cd ..
          flutter_rust_bridge_codegen generate
          cd rust

          # Phase 3: Rebuild without dev_skip_frb to include frb_generated.rs
          echo "--- Phase 3: Final build with FRB bindings ---"
          cargo ndk \
            --target aarch64-linux-android \
            --target armv7-linux-androideabi \
            --target x86_64-linux-android \
            --target i686-linux-android \
            --platform 21 \
            --output-dir ../android/app/src/main/jniLibs \
            build --release

          echo "--- Built .so files ---"
          find ../android/app/src/main/jniLibs -name "*.so" -ls

      - name: Build debug APK
        script: |
          cd identity_agent_ui
          flutter build apk --debug

      - name: Build release APK
        script: |
          cd identity_agent_ui
          flutter build apk --release

    artifacts:
      - identity_agent_ui/build/app/outputs/flutter-apk/*.apk

  ios-release:
    name: iOS Release (with Rust KERI Bridge)
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      flutter: 3.22.0
      xcode: latest
      cocoapods: default
      groups:
        - ios_credentials
      vars:
        BUNDLE_ID: "com.identityagent.identityAgentUi"
    scripts:
      - name: Install Rust toolchain and iOS targets
        script: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source "$HOME/.cargo/env"
          rustup target add aarch64-apple-ios
          rustup target add aarch64-apple-ios-sim
          echo "--- Rust version ---"
          rustc --version
          cargo --version

      - name: Install FRB codegen
        script: |
          source "$HOME/.cargo/env"
          cargo install flutter_rust_bridge_codegen --version 2.11.1

      - name: Get Flutter packages
        script: |
          cd identity_agent_ui
          flutter pub get

      - name: Build Rust static library for iOS (device + simulator) with FRB codegen
        script: |
          source "$HOME/.cargo/env"
          cd identity_agent_ui/rust

          # Phase 1: Build with dev_skip_frb so FRB codegen can inspect
          # the compiled library's exported symbols. frb_generated.rs
          # doesn't exist yet, so we skip that module.
          echo "--- Phase 1: Building with dev_skip_frb for FRB codegen inspection ---"
          cargo build --release --target aarch64-apple-ios --features dev_skip_frb
          cargo build --release --target aarch64-apple-ios-sim --features dev_skip_frb

          # Phase 2: Run FRB codegen from the Flutter project root.
          # This generates rust/src/frb_generated.rs and Dart bindings.
          # Requires flutter pub get to have been run first.
          echo "--- Phase 2: Generating FRB bindings ---"
          cd ..
          flutter_rust_bridge_codegen generate
          cd rust

          # Phase 3: Rebuild WITHOUT dev_skip_frb so frb_generated.rs
          # is compiled into the final library.
          echo "--- Phase 3: Final build with FRB bindings ---"
          cargo build --release --target aarch64-apple-ios
          cargo build --release --target aarch64-apple-ios-sim

          echo "--- Built static libraries ---"
          ls -lh target/aarch64-apple-ios/release/libidentity_agent_keri.a
          ls -lh target/aarch64-apple-ios-sim/release/libidentity_agent_keri.a

      - name: Copy Rust libraries to iOS Frameworks
        script: |
          RUST_DIR="identity_agent_ui/rust"
          IOS_DIR="identity_agent_ui/ios"
          LIB="libidentity_agent_keri.a"
          mkdir -p "$IOS_DIR/Frameworks/RustKeri/device"
          mkdir -p "$IOS_DIR/Frameworks/RustKeri/simulator"
          cp "$RUST_DIR/target/aarch64-apple-ios/release/$LIB" \
             "$IOS_DIR/Frameworks/RustKeri/device/$LIB"
          cp "$RUST_DIR/target/aarch64-apple-ios-sim/release/$LIB" \
             "$IOS_DIR/Frameworks/RustKeri/simulator/$LIB"
          echo "--- Libraries placed ---"
          ls -lh "$IOS_DIR/Frameworks/RustKeri/device/$LIB"
          ls -lh "$IOS_DIR/Frameworks/RustKeri/simulator/$LIB"

      - name: Install CocoaPods dependencies
        script: |
          cd identity_agent_ui/ios
          pod install

      - name: Build iOS IPA (release)
        script: |
          cd identity_agent_ui
          flutter build ipa --release --no-codesign

    artifacts:
      - identity_agent_ui/build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

  windows-release:
    name: Windows Release (Desktop)
    max_build_duration: 60
    instance_type: windows_x2
    environment:
      flutter: 3.22.0
    scripts:
      - name: Install Go toolchain
        script: |
          choco install golang -y
          $env:Path = "C:\Program Files\Go\bin;$env:Path"
          go version

      - name: Build Go backend (Windows)
        script: |
          $env:Path = "C:\Program Files\Go\bin;$env:Path"
          $env:CGO_ENABLED = "0"
          $env:GOOS = "windows"
          $env:GOARCH = "amd64"
          cd identity-agent-core
          go build -o bin\identity-agent-core.exe .
          Write-Host "--- Go binary ---"
          Get-Item bin\identity-agent-core.exe

      - name: Get Flutter packages
        script: |
          cd identity_agent_ui
          flutter pub get

      - name: Build Flutter Windows app
        script: |
          cd identity_agent_ui
          flutter build windows --release

      - name: Bundle Go backend and KERI driver with Flutter app
        script: |
          $BUNDLE = "identity_agent_ui\build\windows\x64\runner\Release"
          mkdir -p "$BUNDLE\backend"
          Copy-Item "identity-agent-core\bin\identity-agent-core.exe" "$BUNDLE\backend\"
          Copy-Item -Recurse "drivers\keri-core" "$BUNDLE\backend\keri-driver"
          Write-Host "--- Bundle contents ---"
          Get-ChildItem -Recurse "$BUNDLE\backend"

      - name: Create ZIP archive
        script: |
          $BUNDLE = "identity_agent_ui\build\windows\x64\runner\Release"
          Compress-Archive -Path "$BUNDLE\*" -DestinationPath "identity-agent-windows-x64.zip"
          Write-Host "--- Archive ---"
          Get-Item "identity-agent-windows-x64.zip"

    artifacts:
      - identity-agent-windows-x64.zip

  macos-release:
    name: macOS Release (Desktop)
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: 3.22.0
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install Go toolchain
        script: |
          brew install go
          go version

      - name: Build Go backend (macOS universal)
        script: |
          cd identity-agent-core
          CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -o bin/identity-agent-core-arm64 .
          CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o bin/identity-agent-core-amd64 .
          lipo -create -output bin/identity-agent-core bin/identity-agent-core-arm64 bin/identity-agent-core-amd64
          echo "--- Go universal binary ---"
          file bin/identity-agent-core
          ls -lh bin/identity-agent-core

      - name: Get Flutter packages
        script: |
          cd identity_agent_ui
          flutter pub get

      - name: Build Flutter macOS app
        script: |
          cd identity_agent_ui
          flutter build macos --release

      - name: Bundle Go backend and KERI driver into .app
        script: |
          APP="identity_agent_ui/build/macos/Build/Products/Release/Identity Agent.app"
          RESOURCES="$APP/Contents/Resources"
          mkdir -p "$RESOURCES/backend"
          cp identity-agent-core/bin/identity-agent-core "$RESOURCES/backend/"
          cp -r drivers/keri-core "$RESOURCES/backend/keri-driver"
          chmod +x "$RESOURCES/backend/identity-agent-core"
          echo "--- Bundle contents ---"
          ls -la "$RESOURCES/backend/"

      - name: Create DMG archive
        script: |
          APP="identity_agent_ui/build/macos/Build/Products/Release/Identity Agent.app"
          hdiutil create -volname "Identity Agent" \
            -srcfolder "$APP" \
            -ov -format UDZO \
            "identity-agent-macos.dmg"
          echo "--- DMG ---"
          ls -lh identity-agent-macos.dmg

    artifacts:
      - identity-agent-macos.dmg

  linux-release:
    name: Linux Release (Desktop)
    max_build_duration: 60
    instance_type: linux_x2
    environment:
      flutter: 3.22.0
    scripts:
      - name: Install system dependencies
        script: |
          sudo apt-get update
          sudo apt-get install -y \
            clang cmake ninja-build pkg-config \
            libgtk-3-dev liblzma-dev libstdc++-12-dev \
            golang-go python3 python3-pip python3-venv
          go version

      - name: Build Go backend (Linux)
        script: |
          cd identity-agent-core
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o bin/identity-agent-core .
          echo "--- Go binary ---"
          file bin/identity-agent-core
          ls -lh bin/identity-agent-core

      - name: Get Flutter packages
        script: |
          cd identity_agent_ui
          flutter pub get

      - name: Build Flutter Linux app
        script: |
          cd identity_agent_ui
          flutter build linux --release

      - name: Bundle Go backend and KERI driver with Flutter app
        script: |
          BUNDLE="identity_agent_ui/build/linux/x64/release/bundle"
          mkdir -p "$BUNDLE/backend"
          cp identity-agent-core/bin/identity-agent-core "$BUNDLE/backend/"
          cp -r drivers/keri-core "$BUNDLE/backend/keri-driver"
          chmod +x "$BUNDLE/backend/identity-agent-core"
          echo "--- Bundle contents ---"
          ls -la "$BUNDLE/backend/"

      - name: Create tarball archive
        script: |
          BUNDLE="identity_agent_ui/build/linux/x64/release/bundle"
          tar -czf identity-agent-linux-x64.tar.gz -C "$BUNDLE" .
          echo "--- Archive ---"
          ls -lh identity-agent-linux-x64.tar.gz

    artifacts:
      - identity-agent-linux-x64.tar.gz
