workflows:
  android-release:
    name: Android Release (with Rust KERI Bridge)
    max_build_duration: 90
    instance_type: linux_x2
    environment:
      flutter: 3.22.0
      java: 17
    scripts:
      - name: Install Rust toolchain and Android targets
        script: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source "$HOME/.cargo/env"
          rustup target add \
            aarch64-linux-android \
            armv7-linux-androideabi \
            x86_64-linux-android \
            i686-linux-android
          cargo install cargo-ndk
          echo "--- Rust version ---"
          rustc --version
          cargo --version
          cargo ndk --version

      - name: Configure Android NDK for Rust
        script: |
          source "$HOME/.cargo/env"
          export ANDROID_NDK_HOME="$ANDROID_SDK_ROOT/ndk/$(ls $ANDROID_SDK_ROOT/ndk/ | sort -V | tail -1)"
          echo "Using NDK: $ANDROID_NDK_HOME"
          echo "ANDROID_NDK_HOME=$ANDROID_NDK_HOME" >> $CM_ENV

      - name: Build Rust library for Android via cargo-ndk
        script: |
          source "$HOME/.cargo/env"
          cd identity_agent_ui/rust
          cargo ndk \
            --target aarch64-linux-android \
            --target armv7-linux-androideabi \
            --target x86_64-linux-android \
            --target i686-linux-android \
            --platform 21 \
            --output-dir ../android/app/src/main/jniLibs \
            build --release
          echo "--- Built .so files ---"
          find ../android/app/src/main/jniLibs -name "*.so" -ls

      - name: Generate flutter_rust_bridge bindings
        script: |
          source "$HOME/.cargo/env"
          cargo install flutter_rust_bridge_codegen --version 2.7.0
          cd identity_agent_ui
          flutter_rust_bridge_codegen generate

      - name: Set up local properties
        script: |
          cd identity_agent_ui
          echo "flutter.sdk=$HOME/programs/flutter" > android/local.properties
          echo "sdk.dir=$ANDROID_SDK_ROOT" >> android/local.properties

      - name: Get Flutter packages
        script: |
          cd identity_agent_ui
          flutter pub get

      - name: Build debug APK
        script: |
          cd identity_agent_ui
          flutter build apk --debug

      - name: Build release APK
        script: |
          cd identity_agent_ui
          flutter build apk --release

    artifacts:
      - identity_agent_ui/build/app/outputs/flutter-apk/*.apk
