// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/keri_bridge.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -205849683;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'identity_agent_keri',
    ioDirectory: 'rust/target/release/',
    webPrefix: 'pkg/',
  );
}

abstract class RustLibApi extends BaseApi {
  String crateApiKeriBridgeCesrEncode({required String rawSigB64});

  String crateApiKeriBridgeGetCurrentKel({required String name});

  InceptionResult crateApiKeriBridgeInceptAid(
      {required String name, required String code});

  HybridInceptionBridgeResult crateApiKeriBridgeInceptHybridAid(
      {required bool synthetic});

  InteractResult crateApiKeriBridgeInteractAid(
      {required String name, required String sealDataJson});

  bool crateApiKeriBridgePqcRustRoundtripSmoke();

  RotationResult crateApiKeriBridgeRotateAid({required String name});

  SignResult crateApiKeriBridgeSignPayload(
      {required String name, required List<int> data});

  bool crateApiKeriBridgeVerifySignature(
      {required List<int> data,
      required String signature,
      required String publicKey});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  String crateApiKeriBridgeCesrEncode({required String rawSigB64}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(rawSigB64, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiKeriBridgeCesrEncodeConstMeta,
      argValues: [rawSigB64],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiKeriBridgeCesrEncodeConstMeta =>
      const TaskConstMeta(
        debugName: "cesr_encode",
        argNames: ["rawSigB64"],
      );

  @override
  String crateApiKeriBridgeGetCurrentKel({required String name}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(name, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiKeriBridgeGetCurrentKelConstMeta,
      argValues: [name],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiKeriBridgeGetCurrentKelConstMeta =>
      const TaskConstMeta(
        debugName: "get_current_kel",
        argNames: ["name"],
      );

  @override
  InceptionResult crateApiKeriBridgeInceptAid(
      {required String name, required String code}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(name, serializer);
        sse_encode_String(code, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_inception_result,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiKeriBridgeInceptAidConstMeta,
      argValues: [name, code],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiKeriBridgeInceptAidConstMeta =>
      const TaskConstMeta(
        debugName: "incept_aid",
        argNames: ["name", "code"],
      );

  @override
  HybridInceptionBridgeResult crateApiKeriBridgeInceptHybridAid(
      {required bool synthetic}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_bool(synthetic, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_hybrid_inception_bridge_result,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiKeriBridgeInceptHybridAidConstMeta,
      argValues: [synthetic],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiKeriBridgeInceptHybridAidConstMeta =>
      const TaskConstMeta(
        debugName: "incept_hybrid_aid",
        argNames: ["synthetic"],
      );

  @override
  InteractResult crateApiKeriBridgeInteractAid(
      {required String name, required String sealDataJson}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(name, serializer);
        sse_encode_String(sealDataJson, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_interact_result,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiKeriBridgeInteractAidConstMeta,
      argValues: [name, sealDataJson],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiKeriBridgeInteractAidConstMeta =>
      const TaskConstMeta(
        debugName: "interact_aid",
        argNames: ["name", "sealDataJson"],
      );

  @override
  bool crateApiKeriBridgePqcRustRoundtripSmoke() {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiKeriBridgePqcRustRoundtripSmokeConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiKeriBridgePqcRustRoundtripSmokeConstMeta =>
      const TaskConstMeta(
        debugName: "pqc_rust_roundtrip_smoke",
        argNames: [],
      );

  @override
  RotationResult crateApiKeriBridgeRotateAid({required String name}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(name, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_rotation_result,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiKeriBridgeRotateAidConstMeta,
      argValues: [name],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiKeriBridgeRotateAidConstMeta =>
      const TaskConstMeta(
        debugName: "rotate_aid",
        argNames: ["name"],
      );

  @override
  SignResult crateApiKeriBridgeSignPayload(
      {required String name, required List<int> data}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(name, serializer);
        sse_encode_list_prim_u_8_loose(data, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_sign_result,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiKeriBridgeSignPayloadConstMeta,
      argValues: [name, data],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiKeriBridgeSignPayloadConstMeta =>
      const TaskConstMeta(
        debugName: "sign_payload",
        argNames: ["name", "data"],
      );

  @override
  bool crateApiKeriBridgeVerifySignature(
      {required List<int> data,
      required String signature,
      required String publicKey}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(data, serializer);
        sse_encode_String(signature, serializer);
        sse_encode_String(publicKey, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiKeriBridgeVerifySignatureConstMeta,
      argValues: [data, signature, publicKey],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiKeriBridgeVerifySignatureConstMeta =>
      const TaskConstMeta(
        debugName: "verify_signature",
        argNames: ["data", "signature", "publicKey"],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  HybridInceptionBridgeResult dco_decode_hybrid_inception_bridge_result(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return HybridInceptionBridgeResult(
      aid: dco_decode_String(arr[0]),
      said: dco_decode_String(arr[1]),
      inceptionEvent: dco_decode_String(arr[2]),
      rawBytesB64: dco_decode_String(arr[3]),
      cipherSuite: dco_decode_String(arr[4]),
      publicKey: dco_decode_String(arr[5]),
      nextKeyDigest: dco_decode_String(arr[6]),
    );
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  InceptionResult dco_decode_inception_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return InceptionResult(
      aid: dco_decode_String(arr[0]),
      publicKey: dco_decode_String(arr[1]),
      kel: dco_decode_String(arr[2]),
    );
  }

  @protected
  InteractResult dco_decode_interact_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return InteractResult(
      aid: dco_decode_String(arr[0]),
      said: dco_decode_String(arr[1]),
      sequenceNumber: dco_decode_i_64(arr[2]),
      kelEntry: dco_decode_String(arr[3]),
      rawBytesB64: dco_decode_String(arr[4]),
    );
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  RotationResult dco_decode_rotation_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return RotationResult(
      aid: dco_decode_String(arr[0]),
      newPublicKey: dco_decode_String(arr[1]),
      kel: dco_decode_String(arr[2]),
    );
  }

  @protected
  SignResult dco_decode_sign_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return SignResult(
      signature: dco_decode_String(arr[0]),
      publicKey: dco_decode_String(arr[1]),
    );
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  HybridInceptionBridgeResult sse_decode_hybrid_inception_bridge_result(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_aid = sse_decode_String(deserializer);
    var var_said = sse_decode_String(deserializer);
    var var_inceptionEvent = sse_decode_String(deserializer);
    var var_rawBytesB64 = sse_decode_String(deserializer);
    var var_cipherSuite = sse_decode_String(deserializer);
    var var_publicKey = sse_decode_String(deserializer);
    var var_nextKeyDigest = sse_decode_String(deserializer);
    return HybridInceptionBridgeResult(
        aid: var_aid,
        said: var_said,
        inceptionEvent: var_inceptionEvent,
        rawBytesB64: var_rawBytesB64,
        cipherSuite: var_cipherSuite,
        publicKey: var_publicKey,
        nextKeyDigest: var_nextKeyDigest);
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  InceptionResult sse_decode_inception_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_aid = sse_decode_String(deserializer);
    var var_publicKey = sse_decode_String(deserializer);
    var var_kel = sse_decode_String(deserializer);
    return InceptionResult(
        aid: var_aid, publicKey: var_publicKey, kel: var_kel);
  }

  @protected
  InteractResult sse_decode_interact_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_aid = sse_decode_String(deserializer);
    var var_said = sse_decode_String(deserializer);
    var var_sequenceNumber = sse_decode_i_64(deserializer);
    var var_kelEntry = sse_decode_String(deserializer);
    var var_rawBytesB64 = sse_decode_String(deserializer);
    return InteractResult(
        aid: var_aid,
        said: var_said,
        sequenceNumber: var_sequenceNumber,
        kelEntry: var_kelEntry,
        rawBytesB64: var_rawBytesB64);
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  RotationResult sse_decode_rotation_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_aid = sse_decode_String(deserializer);
    var var_newPublicKey = sse_decode_String(deserializer);
    var var_kel = sse_decode_String(deserializer);
    return RotationResult(
        aid: var_aid, newPublicKey: var_newPublicKey, kel: var_kel);
  }

  @protected
  SignResult sse_decode_sign_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_signature = sse_decode_String(deserializer);
    var var_publicKey = sse_decode_String(deserializer);
    return SignResult(signature: var_signature, publicKey: var_publicKey);
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_hybrid_inception_bridge_result(
      HybridInceptionBridgeResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.aid, serializer);
    sse_encode_String(self.said, serializer);
    sse_encode_String(self.inceptionEvent, serializer);
    sse_encode_String(self.rawBytesB64, serializer);
    sse_encode_String(self.cipherSuite, serializer);
    sse_encode_String(self.publicKey, serializer);
    sse_encode_String(self.nextKeyDigest, serializer);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_inception_result(
      InceptionResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.aid, serializer);
    sse_encode_String(self.publicKey, serializer);
    sse_encode_String(self.kel, serializer);
  }

  @protected
  void sse_encode_interact_result(
      InteractResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.aid, serializer);
    sse_encode_String(self.said, serializer);
    sse_encode_i_64(self.sequenceNumber, serializer);
    sse_encode_String(self.kelEntry, serializer);
    sse_encode_String(self.rawBytesB64, serializer);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
      List<int> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer
        .putUint8List(self is Uint8List ? self : Uint8List.fromList(self));
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_rotation_result(
      RotationResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.aid, serializer);
    sse_encode_String(self.newPublicKey, serializer);
    sse_encode_String(self.kel, serializer);
  }

  @protected
  void sse_encode_sign_result(SignResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.signature, serializer);
    sse_encode_String(self.publicKey, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
