// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `bridge_hybrid_result`, `get_or_init_instances`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `KeriInstance`

/// hybrid PQC C1 — build IA-HYBRID-1 four-key inception (synthetic harness material when synthetic=true).
HybridInceptionBridgeResult inceptHybridAid({required bool synthetic}) =>
    RustLib.instance.api
        .crateApiKeriBridgeInceptHybridAid(synthetic: synthetic);

/// C4 mobile PQC smoke test — delegates to pure-Rust ml-dsa/ml-kem round-trip crate.
bool pqcRustRoundtripSmoke() =>
    RustLib.instance.api.crateApiKeriBridgePqcRustRoundtripSmoke();

InceptionResult inceptAid({required String name, required String code}) =>
    RustLib.instance.api.crateApiKeriBridgeInceptAid(name: name, code: code);

RotationResult rotateAid({required String name}) =>
    RustLib.instance.api.crateApiKeriBridgeRotateAid(name: name);

SignResult signPayload({required String name, required List<int> data}) =>
    RustLib.instance.api.crateApiKeriBridgeSignPayload(name: name, data: data);

String getCurrentKel({required String name}) =>
    RustLib.instance.api.crateApiKeriBridgeGetCurrentKel(name: name);

bool verifySignature(
        {required List<int> data,
        required String signature,
        required String publicKey}) =>
    RustLib.instance.api.crateApiKeriBridgeVerifySignature(
        data: data, signature: signature, publicKey: publicKey);

/// Create a KERI interaction (IXN) event anchoring [seal_data_json] in the KEL.
/// [seal_data_json] is a JSON array of seal maps, e.g. '[{"d":"<SAID>","i":"<AID>","s":"<schema>"}]'.
/// Returns the IXN event bytes (base64) for Dart to sign with the current key.
InteractResult interactAid(
        {required String name, required String sealDataJson}) =>
    RustLib.instance.api
        .crateApiKeriBridgeInteractAid(name: name, sealDataJson: sealDataJson);

/// CESR-encode a raw 64-byte Ed25519 signature (base64-encoded input) into the
/// '0B...' 88-character CESR Cigar format used by KERI witness receipts and event signatures.
///
/// Algorithm (identical to Python's coring.Cigar(raw=sig, code=MtrDex.Ed25519_Sig).qb64):
///   1. base64-decode raw_sig_b64 → 64 raw bytes
///   2. prepend two zero lead bytes → 66 bytes
///   3. base64url-encode (no padding) → 88 chars
///   4. replace leading 2 chars with '0B'
String cesrEncode({required String rawSigB64}) =>
    RustLib.instance.api.crateApiKeriBridgeCesrEncode(rawSigB64: rawSigB64);

class HybridInceptionBridgeResult {
  final String aid;
  final String said;
  final String inceptionEvent;
  final String rawBytesB64;
  final String cipherSuite;
  final String publicKey;
  final String nextKeyDigest;

  const HybridInceptionBridgeResult({
    required this.aid,
    required this.said,
    required this.inceptionEvent,
    required this.rawBytesB64,
    required this.cipherSuite,
    required this.publicKey,
    required this.nextKeyDigest,
  });

  @override
  int get hashCode =>
      aid.hashCode ^
      said.hashCode ^
      inceptionEvent.hashCode ^
      rawBytesB64.hashCode ^
      cipherSuite.hashCode ^
      publicKey.hashCode ^
      nextKeyDigest.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HybridInceptionBridgeResult &&
          runtimeType == other.runtimeType &&
          aid == other.aid &&
          said == other.said &&
          inceptionEvent == other.inceptionEvent &&
          rawBytesB64 == other.rawBytesB64 &&
          cipherSuite == other.cipherSuite &&
          publicKey == other.publicKey &&
          nextKeyDigest == other.nextKeyDigest;
}

class InceptionResult {
  final String aid;
  final String publicKey;
  final String kel;

  const InceptionResult({
    required this.aid,
    required this.publicKey,
    required this.kel,
  });

  @override
  int get hashCode => aid.hashCode ^ publicKey.hashCode ^ kel.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InceptionResult &&
          runtimeType == other.runtimeType &&
          aid == other.aid &&
          publicKey == other.publicKey &&
          kel == other.kel;
}

class InteractResult {
  final String aid;
  final String said;
  final PlatformInt64 sequenceNumber;
  final String kelEntry;
  final String rawBytesB64;

  const InteractResult({
    required this.aid,
    required this.said,
    required this.sequenceNumber,
    required this.kelEntry,
    required this.rawBytesB64,
  });

  @override
  int get hashCode =>
      aid.hashCode ^
      said.hashCode ^
      sequenceNumber.hashCode ^
      kelEntry.hashCode ^
      rawBytesB64.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InteractResult &&
          runtimeType == other.runtimeType &&
          aid == other.aid &&
          said == other.said &&
          sequenceNumber == other.sequenceNumber &&
          kelEntry == other.kelEntry &&
          rawBytesB64 == other.rawBytesB64;
}

class RotationResult {
  final String aid;
  final String newPublicKey;
  final String kel;

  const RotationResult({
    required this.aid,
    required this.newPublicKey,
    required this.kel,
  });

  @override
  int get hashCode => aid.hashCode ^ newPublicKey.hashCode ^ kel.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RotationResult &&
          runtimeType == other.runtimeType &&
          aid == other.aid &&
          newPublicKey == other.newPublicKey &&
          kel == other.kel;
}

class SignResult {
  final String signature;
  final String publicKey;

  const SignResult({
    required this.signature,
    required this.publicKey,
  });

  @override
  int get hashCode => signature.hashCode ^ publicKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SignResult &&
          runtimeType == other.runtimeType &&
          signature == other.signature &&
          publicKey == other.publicKey;
}
