import 'dart:typed_data';

import 'package:agent_client/attestation/snp_report.dart';
import 'package:test/test.dart';

/// A golden vector, shared with the server-side reader of the same report.
///
/// A report is produced by one implementation and read by another. Two readers
/// of a fixed binary layout, written from the same specification, eventually
/// disagree about something — a field offset, a byte order, a length — and the
/// disagreement is silent: this side simply rejects genuine reports, or accepts
/// ones it should not, with nothing in the symptom pointing at the cause. Both
/// sides assert the values below against the same input, so a drift on either
/// side fails a test instead of shipping.
///
/// The vector is synthetic, generated by a rule both sides reproduce exactly.
/// A captured report would tie this test to one particular processor and put
/// that processor's identifier in the repository, neither of which is needed to
/// exercise the layout.
void main() {
  /// Generated by a rule the Go test reproduces byte for byte.
  Uint8List vector() {
    final r = Uint8List(SnpReport.reportSize);
    for (var i = 0; i < r.length; i++) {
      r[i] = (i * 31 + 7) & 0xFF;
    }
    return r;
  }

  String hex(Uint8List b) =>
      b.map((x) => x.toRadixString(16).padLeft(2, '0')).join();

  group('the Dart reader agrees with the host implementation', () {
    late SnpReport report;
    setUp(() => report = SnpReport(vector()));

    test('measurement', () {
      expect(
          hex(report.measurement),
          '7796b5d4f31231506f8eadcceb0a29486786a5c4e30221405f7e9dbcdbfa1938'
          '577695b4d3f211304f6e8daccbea0928');
    });

    test('reportData', () {
      expect(
          hex(report.reportData),
          'b7d6f51433527190afceed0c2b4a6988a7c6e504234261809fbeddfc1b3a5978'
          '97b6d5f4133251708faecdec0b2a496887a6c5e4032241607f9ebddcfb1a3958');
    });

    test('chipId', () {
      expect(
          hex(report.chipId),
          '6786a5c4e30221405f7e9dbcdbfa1938577695b4d3f211304f6e8daccbea0928'
          '476685a4c3e201203f5e7d9cbbdaf91837567594b3d2f1102f4e6d8cabcae908');
    });

    test('reportedTcb', () {
      expect(hex(report.reportedTcb), '87a6c5e403224160');
    });

    // The one most likely to be wrong, and the one whose failure looks least
    // like its cause: r and s are little-endian and BigInt is big-endian.
    test('signature r and s, read little-endian', () {
      expect(
          report.signatureR.toString(),
          '85201091780046775290998163368760219651589607763028562338112245954'
          '0969788291302702716556139240650509681896456307414833799767408534'
          '158401107565966922990612126943351031563879');
      expect(
          report.signatureS.toString(),
          '17834794609261754492447186672578420515294029982794048922233846058'
          '1236437212129797707626075433105961245505206724381817452122888689'
          '464161214586971872754209733380077028791631391');
    });
  });

  group('the REPORT_DATA binding matches the host byte for byte', () {
    test('golden vector', () {
      expect(
          hex(bindReportData('EXAMPLEaid123')),
          '22095b6912ba3636ee66e2cf4bc11161c86a3c6aaa4c7bddc084fab403835335'
          '0000000000000000000000000000000000000000000000000000000000000000');
    });

    test('the tail is zero, not padding to be reused', () {
      final b = bindReportData('anything');
      expect(b.length, 64);
      expect(b.sublist(32).every((x) => x == 0), isTrue);
    });

    test('a different value gives a different binding', () {
      expect(hex(bindReportData('a')), isNot(hex(bindReportData('b'))));
    });

    test('the domain separator is part of the input', () {
      // Hashing the bare value must not produce the same result, or a value
      // hashed for some other purpose could be replayed as a binding.
      expect(hex(bindReportData('x')),
          isNot(hex(bindReportData('IA-SNP-BIND-V1\nx'))));
    });
  });

  group('binding checks reject what they should', () {
    test('a report bound to another instance does not pass', () {
      final r = Uint8List(SnpReport.reportSize);
      r.setRange(0x50, 0x50 + 64, bindReportData('instance-one'));
      expect(SnpReport(r).isBoundTo('instance-one'), isTrue);
      expect(SnpReport(r).isBoundTo('instance-two'), isFalse);
    });

    // A prefix match would accept a report whose first bytes were right and
    // whose remainder was chosen freely.
    test('a matching prefix is not enough', () {
      final r = Uint8List(SnpReport.reportSize);
      final good = bindReportData('instance-one');
      r.setRange(0x50, 0x50 + 64, good);
      r[0x50 + 31] ^=
          0x01; // last byte of the digest, inside the 32 that matter
      expect(SnpReport(r).isBoundTo('instance-one'), isFalse);
    });
  });

  group('a report that is valid but describes an unsealed guest', () {
    // Verifying the signature and ignoring this would accept a machine the
    // operator is permitted to attach a debugger to.
    test('debugAllowed is read from the policy bit', () {
      final off = Uint8List(SnpReport.reportSize);
      expect(SnpReport(off).debugAllowed, isFalse);

      final on = Uint8List(SnpReport.reportSize);
      ByteData.sublistView(on, 0x08, 0x10).setUint64(0, 1 << 19, Endian.little);
      expect(SnpReport(on).debugAllowed, isTrue);
    });
  });

  test('a short report is refused rather than read as zeroes', () {
    expect(() => SnpReport(Uint8List(100)), throwsArgumentError);
  });
}
