// GENERATED BY flutter_rust_bridge. DO NOT EDIT.
// This file is a placeholder that will be overwritten by
// `flutter_rust_bridge_codegen generate` during CI/CD build.
//
// These classes mirror the Rust structs in rust/src/api/keri_bridge.rs.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

class InceptionResult {
  final String aid;
  final String publicKey;
  final String kel;

  const InceptionResult({
    required this.aid,
    required this.publicKey,
    required this.kel,
  });
}

class RotationResult {
  final String aid;
  final String newPublicKey;
  final String kel;

  const RotationResult({
    required this.aid,
    required this.newPublicKey,
    required this.kel,
  });
}

class SignResult {
  final String signature;
  final String publicKey;

  const SignResult({
    required this.signature,
    required this.publicKey,
  });
}

InceptionResult inceptAid({required String name, required String code}) =>
    RustLib.instance.api
        .crateApiKeriBridgeInceptAid(name: name, code: code);

RotationResult rotateAid({required String name}) =>
    RustLib.instance.api.crateApiKeriBridgeRotateAid(name: name);

SignResult signPayload({required String name, required List<int> data}) =>
    RustLib.instance.api
        .crateApiKeriBridgeSignPayload(name: name, data: data);

String getCurrentKel({required String name}) =>
    RustLib.instance.api.crateApiKeriBridgeGetCurrentKel(name: name);

bool verifySignature(
        {required List<int> data,
        required String signature,
        required String publicKey}) =>
    RustLib.instance.api.crateApiKeriBridgeVerifySignature(
        data: data, signature: signature, publicKey: publicKey);
