// GENERATED BY flutter_rust_bridge — PLACEHOLDER
// This file will be overwritten by `flutter_rust_bridge_codegen generate`
// during the Codemagic CI/CD build. It exists so that flutter analyze passes
// during development without a compiled native library.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'dart:async';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'api/keri_bridge.dart' as keri_api;

class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  RustLib._();
  static final instance = RustLib._();

  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
  }) =>
      instance.initImpl(
        api: api,
        handler: handler,
        externalLibrary: externalLibrary,
      );

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      ExternalLibraryLoaderConfig(
        stem: 'identity_agent_keri',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 0;
}

abstract class RustLibApi extends BaseApi {
  keri_api.InceptionResult crateApiKeriBridgeInceptAid(
      {required String name, required String code});

  keri_api.RotationResult crateApiKeriBridgeRotateAid({required String name});

  keri_api.SignResult crateApiKeriBridgeSignPayload(
      {required String name, required List<int> data});

  String crateApiKeriBridgeGetCurrentKel({required String name});

  bool crateApiKeriBridgeVerifySignature(
      {required List<int> data,
      required String signature,
      required String publicKey});
}

class RustLibApiImpl extends BaseApiImpl<RustLibWire> implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  keri_api.InceptionResult crateApiKeriBridgeInceptAid(
      {required String name, required String code}) {
    throw UnimplementedError(
        'Placeholder — run flutter_rust_bridge_codegen generate');
  }

  @override
  keri_api.RotationResult crateApiKeriBridgeRotateAid(
      {required String name}) {
    throw UnimplementedError(
        'Placeholder — run flutter_rust_bridge_codegen generate');
  }

  @override
  keri_api.SignResult crateApiKeriBridgeSignPayload(
      {required String name, required List<int> data}) {
    throw UnimplementedError(
        'Placeholder — run flutter_rust_bridge_codegen generate');
  }

  @override
  String crateApiKeriBridgeGetCurrentKel({required String name}) {
    throw UnimplementedError(
        'Placeholder — run flutter_rust_bridge_codegen generate');
  }

  @override
  bool crateApiKeriBridgeVerifySignature(
      {required List<int> data,
      required String signature,
      required String publicKey}) {
    throw UnimplementedError(
        'Placeholder — run flutter_rust_bridge_codegen generate');
  }
}

class RustLibWire extends BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}
